/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: test/simple.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "test/simple.pb-c.h"
void   foo__simple__init
                     (Foo__Simple         *message)
{
  static const Foo__Simple init_value = FOO__SIMPLE__INIT;
  *message = init_value;
}
size_t foo__simple__get_packed_size
                     (const Foo__Simple *message)
{
  assert(message->base.descriptor == &foo__simple__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t foo__simple__pack
                     (const Foo__Simple *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &foo__simple__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t foo__simple__pack_to_buffer
                     (const Foo__Simple *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &foo__simple__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Foo__Simple *
       foo__simple__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Foo__Simple *)
     protobuf_c_message_unpack (&foo__simple__descriptor,
                                allocator, len, data);
}
void   foo__simple__free_unpacked
                     (Foo__Simple *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &foo__simple__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor foo__simple__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Foo__Simple, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Foo__Simple, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "other",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Foo__Simple, n_other),
    offsetof(Foo__Simple, other),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned foo__simple__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = name */
  2,   /* field[2] = other */
};
static const ProtobufCIntRange foo__simple__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor foo__simple__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "foo.Simple",
  "Simple",
  "Foo__Simple",
  "foo",
  sizeof(Foo__Simple),
  3,
  foo__simple__field_descriptors,
  foo__simple__field_indices_by_name,
  1,  foo__simple__number_ranges,
  (ProtobufCMessageInit) foo__simple__init,
  NULL,NULL,NULL    /* reserved[123] */
};
