/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: test/test.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "test/test.pb-c.h"
void   foo__person__phone_number__comment__init
                     (Foo__Person__PhoneNumber__Comment         *message)
{
  static const Foo__Person__PhoneNumber__Comment init_value = FOO__PERSON__PHONE_NUMBER__COMMENT__INIT;
  *message = init_value;
}
void   foo__person__phone_number__init
                     (Foo__Person__PhoneNumber         *message)
{
  static const Foo__Person__PhoneNumber init_value = FOO__PERSON__PHONE_NUMBER__INIT;
  *message = init_value;
}
void   foo__person__init
                     (Foo__Person         *message)
{
  static const Foo__Person init_value = FOO__PERSON__INIT;
  *message = init_value;
}
size_t foo__person__get_packed_size
                     (const Foo__Person *message)
{
  assert(message->base.descriptor == &foo__person__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t foo__person__pack
                     (const Foo__Person *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &foo__person__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t foo__person__pack_to_buffer
                     (const Foo__Person *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &foo__person__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Foo__Person *
       foo__person__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Foo__Person *)
     protobuf_c_message_unpack (&foo__person__descriptor,
                                allocator, len, data);
}
void   foo__person__free_unpacked
                     (Foo__Person *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &foo__person__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   foo__lookup_result__init
                     (Foo__LookupResult         *message)
{
  static const Foo__LookupResult init_value = FOO__LOOKUP_RESULT__INIT;
  *message = init_value;
}
size_t foo__lookup_result__get_packed_size
                     (const Foo__LookupResult *message)
{
  assert(message->base.descriptor == &foo__lookup_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t foo__lookup_result__pack
                     (const Foo__LookupResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &foo__lookup_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t foo__lookup_result__pack_to_buffer
                     (const Foo__LookupResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &foo__lookup_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Foo__LookupResult *
       foo__lookup_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Foo__LookupResult *)
     protobuf_c_message_unpack (&foo__lookup_result__descriptor,
                                allocator, len, data);
}
void   foo__lookup_result__free_unpacked
                     (Foo__LookupResult *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &foo__lookup_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   foo__name__init
                     (Foo__Name         *message)
{
  static const Foo__Name init_value = FOO__NAME__INIT;
  *message = init_value;
}
size_t foo__name__get_packed_size
                     (const Foo__Name *message)
{
  assert(message->base.descriptor == &foo__name__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t foo__name__pack
                     (const Foo__Name *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &foo__name__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t foo__name__pack_to_buffer
                     (const Foo__Name *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &foo__name__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Foo__Name *
       foo__name__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Foo__Name *)
     protobuf_c_message_unpack (&foo__name__descriptor,
                                allocator, len, data);
}
void   foo__name__free_unpacked
                     (Foo__Name *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &foo__name__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor foo__person__phone_number__comment__field_descriptors[1] =
{
  {
    "comment",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Foo__Person__PhoneNumber__Comment, comment),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned foo__person__phone_number__comment__field_indices_by_name[] = {
  0,   /* field[0] = comment */
};
static const ProtobufCIntRange foo__person__phone_number__comment__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor foo__person__phone_number__comment__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "foo.Person.PhoneNumber.Comment",
  "Comment",
  "Foo__Person__PhoneNumber__Comment",
  "foo",
  sizeof(Foo__Person__PhoneNumber__Comment),
  1,
  foo__person__phone_number__comment__field_descriptors,
  foo__person__phone_number__comment__field_indices_by_name,
  1,  foo__person__phone_number__comment__number_ranges,
  (ProtobufCMessageInit) foo__person__phone_number__comment__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor foo__person__phone_number__field_descriptors[3] =
{
  {
    "number",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Foo__Person__PhoneNumber, number),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Foo__Person__PhoneNumber, type),
    &foo__person__phone_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "comment",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Foo__Person__PhoneNumber, comment),
    &foo__person__phone_number__comment__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned foo__person__phone_number__field_indices_by_name[] = {
  2,   /* field[2] = comment */
  0,   /* field[0] = number */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange foo__person__phone_number__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor foo__person__phone_number__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "foo.Person.PhoneNumber",
  "PhoneNumber",
  "Foo__Person__PhoneNumber",
  "foo",
  sizeof(Foo__Person__PhoneNumber),
  3,
  foo__person__phone_number__field_descriptors,
  foo__person__phone_number__field_indices_by_name,
  1,  foo__person__phone_number__number_ranges,
  (ProtobufCMessageInit) foo__person__phone_number__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue foo__person__phone_type__enum_values_by_number[3] =
{
  { "MOBILE", "FOO__PERSON__PHONE_TYPE__MOBILE", 0 },
  { "HOME", "FOO__PERSON__PHONE_TYPE__HOME", 1 },
  { "WORK", "FOO__PERSON__PHONE_TYPE__WORK", 2 },
};
static const ProtobufCIntRange foo__person__phone_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex foo__person__phone_type__enum_values_by_name[3] =
{
  { "HOME", 1 },
  { "MOBILE", 0 },
  { "WORK", 2 },
};
const ProtobufCEnumDescriptor foo__person__phone_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "foo.Person.PhoneType",
  "PhoneType",
  "Foo__Person__PhoneType",
  "foo",
  3,
  foo__person__phone_type__enum_values_by_number,
  3,
  foo__person__phone_type__enum_values_by_name,
  1,
  foo__person__phone_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor foo__person__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Foo__Person, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Foo__Person, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "email",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Foo__Person, email),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phone",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Foo__Person, n_phone),
    offsetof(Foo__Person, phone),
    &foo__person__phone_number__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned foo__person__field_indices_by_name[] = {
  2,   /* field[2] = email */
  1,   /* field[1] = id */
  0,   /* field[0] = name */
  3,   /* field[3] = phone */
};
static const ProtobufCIntRange foo__person__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor foo__person__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "foo.Person",
  "Person",
  "Foo__Person",
  "foo",
  sizeof(Foo__Person),
  4,
  foo__person__field_descriptors,
  foo__person__field_indices_by_name,
  1,  foo__person__number_ranges,
  (ProtobufCMessageInit) foo__person__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor foo__lookup_result__field_descriptors[1] =
{
  {
    "person",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Foo__LookupResult, person),
    &foo__person__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned foo__lookup_result__field_indices_by_name[] = {
  0,   /* field[0] = person */
};
static const ProtobufCIntRange foo__lookup_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor foo__lookup_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "foo.LookupResult",
  "LookupResult",
  "Foo__LookupResult",
  "foo",
  sizeof(Foo__LookupResult),
  1,
  foo__lookup_result__field_descriptors,
  foo__lookup_result__field_indices_by_name,
  1,  foo__lookup_result__number_ranges,
  (ProtobufCMessageInit) foo__lookup_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor foo__name__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Foo__Name, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned foo__name__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange foo__name__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor foo__name__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "foo.Name",
  "Name",
  "Foo__Name",
  "foo",
  sizeof(Foo__Name),
  1,
  foo__name__field_descriptors,
  foo__name__field_indices_by_name,
  1,  foo__name__number_ranges,
  (ProtobufCMessageInit) foo__name__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor foo__dir_lookup__method_descriptors[1] =
{
  { "ByName", &foo__name__descriptor, &foo__lookup_result__descriptor },
};
const unsigned foo__dir_lookup__method_indices_by_name[] = {
  0         /* ByName */
};
const ProtobufCServiceDescriptor foo__dir_lookup__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "foo.DirLookup",
  "DirLookup",
  "Foo__DirLookup",
  "foo",
  1,
  foo__dir_lookup__method_descriptors,
  foo__dir_lookup__method_indices_by_name
};
void foo__dir_lookup__by_name(ProtobufCService *service,
                              const Foo__Name *input,
                              Foo__LookupResult_Closure closure,
                              void *closure_data)
{
  assert(service->descriptor == &foo__dir_lookup__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void foo__dir_lookup__init (Foo__DirLookup_Service *service,
                            Foo__DirLookup_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &foo__dir_lookup__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
